import type { Metadata } from "next";
import Footer from "./_components/Footer";
import "./globals.css";
import { Nunito_Sans, Teko } from "next/font/google";
import Header from "./_components/Header";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
});

const tekoFont = Teko({
  subsets: ["latin"],
  variable: "--font-teko",
});
// const geistMono = localFont({
//   src: "../../public/fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoSans.className} ${tekoFont.variable} antialiased`}
      >
        <div className="background-image" />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
